services:
  - type: web
    name: food-site
    runtime: node
    buildCommand: yarn
    startCommand: yarn start
    nodeVersion: 18.x
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    staticPublishPath: ./frontend
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
